---
# Template configuration files for jboss

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ jboss_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - jboss_enable_selinux
  become: true
